#!/usr/bin/env python3
"""Sub2API monitor template.

Reads scheduled-test results generated by Sub2API itself, normalizes status, optionally switches schedulable state, publishes announcements, and mirrors them to Telegram unless muted.

Configure with environment variables; do not hard-code secrets.
"""

import json
import os
import pathlib
import shlex
import subprocess
import time
import urllib.request

SUB2API_BASE_URL = os.environ.get("SUB2API_BASE_URL", "https://<your-sub2api-host>").rstrip("/")
SUB2API_ADMIN_EMAIL = os.environ.get("SUB2API_ADMIN_EMAIL", "<admin@example.com>")
SUB2API_ADMIN_PASSWORD = os.environ.get("SUB2API_ADMIN_PASSWORD", "<admin-password>")
TELEGRAM_BOT_TOKEN = os.environ.get("TELEGRAM_BOT_TOKEN", "<telegram-bot-token>")
TELEGRAM_CHAT_ID = os.environ.get("SUB2API_MONITOR_CHAT_ID", os.environ.get("SUB2API_BOT_ALLOWED_CHAT_IDS", "<telegram-chat-id>").split(",")[0])
STATE_FILE = os.environ.get("SUB2API_MONITOR_STATE_FILE", "/tmp/sub2api_monitor_state.json")
MUTE_FILE = os.environ.get("SUB2API_BOT_MUTE_FILE", "/tmp/sub2api_bot_mute_until.txt")
DB_NAME = os.environ.get("SUB2API_DB_NAME", "sub2api")
DB_USER = os.environ.get("SUB2API_DB_USER", "postgres")

# Example mapping. Replace IDs and names with your own environment.
MONITORED_ACCOUNTS = json.loads(os.environ.get("SUB2API_MONITORED_ACCOUNTS", '[{"id":100,"name":"South-OpenAI"},{"id":99,"name":"South-Anthropic"}]'))
TOKEN_ROUTER_ACCOUNT_ID = int(os.environ.get("SUB2API_TOKEN_ROUTER_ACCOUNT_ID", "110"))


def run(cmd, timeout=20):
    return subprocess.run(cmd, shell=True, capture_output=True, text=True, timeout=timeout)


def psql(sql, timeout=20):
    cmd = "psql -d " + shlex.quote(DB_NAME) + " -t -A -F '|' -c " + shlex.quote(sql)
    proc = subprocess.run(["su", "-", DB_USER, "-c", cmd], capture_output=True, text=True, timeout=timeout)
    if proc.returncode != 0:
        raise RuntimeError(proc.stderr.strip()[:300])
    return proc.stdout.strip()


def normalize_status(status, error=""):
    text = (str(status or "") + " " + str(error or "")).lower()
    if status == "success":
        return "available"
    if "rate limit" in text or "ratelimit" in text or "429" in text or "quota" in text:
        return "rate_limited"
    return "unavailable"


def latest_result(account_id):
    sql = "SELECT r.status,COALESCE(r.error_message,''),COALESCE(r.latency_ms,0),r.created_at FROM scheduled_test_results r JOIN scheduled_test_plans p ON p.id=r.plan_id WHERE p.account_id=" + str(int(account_id)) + " ORDER BY r.created_at DESC LIMIT 1;"
    out = psql(sql)
    if not out:
        return None
    status, error, latency, created = (out.split("|") + [""] * 4)[:4]
    return {"status": normalize_status(status, error), "raw_status": status, "error": error, "latency_ms": latency, "created_at": created}


def set_schedulable(account_id, enabled):
    value = "true" if enabled else "false"
    psql("UPDATE accounts SET schedulable=" + value + ", updated_at=now() WHERE id=" + str(int(account_id)) + " AND deleted_at IS NULL;")
    psql("INSERT INTO scheduler_outbox(event_type,account_id,payload) VALUES('account_changed'," + str(int(account_id)) + ",'{\"source\":\"monitor\"}'::jsonb);")


def current_schedulable(account_id):
    out = psql("SELECT schedulable FROM accounts WHERE id=" + str(int(account_id)) + " AND deleted_at IS NULL LIMIT 1;")
    return out == "t"


def publish_announcement(title, content):
    sql = "INSERT INTO announcements(title,content,status) VALUES(" + quote(title) + "," + quote(content) + ",'active') RETURNING id;"
    out = psql(sql)
    return out.splitlines()[0] if out else "?"


def quote(v):
    return "'" + str(v).replace("'", "''") + "'"


def muted():
    try:
        until = int(pathlib.Path(MUTE_FILE).read_text().strip())
        return until > int(time.time())
    except Exception:
        return False


def send_telegram(title, content):
    if muted():
        print("Telegram muted, skip push")
        return False
    if TELEGRAM_BOT_TOKEN.startswith("<") or TELEGRAM_CHAT_ID.startswith("<"):
        print("Telegram not configured, skip push")
        return False
    url = "https://api.telegram.org/bot" + TELEGRAM_BOT_TOKEN + "/sendMessage"
    text = title + "\n\n" + content
    if len(text) > 3900:
        text = text[:3900] + "\n..."
    body = json.dumps({"chat_id": TELEGRAM_CHAT_ID, "text": text, "disable_web_page_preview": True}, ensure_ascii=False).encode()
    req = urllib.request.Request(url, data=body, headers={"Content-Type": "application/json"}, method="POST")
    with urllib.request.urlopen(req, timeout=15) as resp:
        return bool(json.loads(resp.read().decode()).get("ok"))


def load_state():
    try:
        return json.loads(pathlib.Path(STATE_FILE).read_text())
    except Exception:
        return {}


def save_state(state):
    pathlib.Path(STATE_FILE).write_text(json.dumps(state, ensure_ascii=False, indent=2))


def main(force=False):
    state = load_state()
    reports = []
    statuses = {}
    for account in MONITORED_ACCOUNTS:
        result = latest_result(account["id"])
        if not result:
            continue
        statuses[int(account["id"])] = result["status"]
        previous = (state.get(str(account["id"])) or {}).get("status")
        state[str(account["id"])] = {"status": result["status"], "checked_at": time.strftime("%Y-%m-%d %H:%M:%S"), "latency_ms": result["latency_ms"]}
        if force or (previous and previous != result["status"]):
            reports.append((account, previous, result))

    # Example routing rule. Adjust for your own accounts.
    if 100 in statuses:
        openai_ok = statuses[100] == "available"
        if current_schedulable(100) != openai_ok:
            set_schedulable(100, openai_ok)
        if current_schedulable(TOKEN_ROUTER_ACCOUNT_ID) == openai_ok:
            set_schedulable(TOKEN_ROUTER_ACCOUNT_ID, not openai_ok)
    if 99 in statuses:
        anth_ok = statuses[99] == "available"
        if current_schedulable(99) != anth_ok:
            set_schedulable(99, anth_ok)

    for account, previous, result in reports:
        title = ("✅" if result["status"] == "available" else "⚠️") + " [Sub2API] " + account["name"] + " 当前 " + result["status"]
        content = "账号：" + account["name"] + "\n状态：" + result["status"] + "\n上次：" + str(previous) + "\n延迟：" + str(result["latency_ms"]) + "ms\n时间：" + result["created_at"]
        announcement_id = publish_announcement(title, content)
        print("announcement", announcement_id, title)
        send_telegram(title, content)

    if not reports:
        print("no state change")
    save_state(state)


if __name__ == "__main__":
    import sys
    main(force="--force" in sys.argv)
